import "./globals.css";
import { NavbarServer, Footer } from "./(global)";
import type { Metadata } from "next";
import "bulma/css/bulma.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) 
{
  return (
    <html lang="en">
      <body
        className={`${inter.className} is-flex is-flex-direction-column is-justify-content-space-between`}>
        <div>
          <NavbarServer />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
